services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"

  feast-cli:
    image: python:3.9-slim
    container_name: feast-cli
    volumes:
      - ./feature_repo:/home/feast/feature_repo
    working_dir: /home/feast/feature_repo
    entrypoint:
      - bash
      - -c
      - |
        pip install feast && sleep infinity

  mlflow:
    image: python:3.9-slim
    container_name: mlflow
    command: >
      bash -c "pip install --no-cache-dir mlflow && \
               mlflow server --backend-store-uri sqlite:///mlflow/mlflow.db \
                             --default-artifact-root /mlflow \
                             --host 0.0.0.0"
    ports:
      - "5001:5000"
    volumes:
      - ./mlflow:/mlflow
